# Generated by Django 4.2.4 on 2023-08-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unitus_', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('CF', models.CharField(max_length=16, unique=True)),
                ('email_p', models.EmailField(max_length=254, unique=True)),
                ('email_u', models.EmailField(max_length=254, unique=True)),
                ('department', models.IntegerField()),
                ('profile', models.IntegerField()),
                ('expired', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
