# Generated by Django 4.2.4 on 2023-08-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unitus_', '0002_user_alter_profile_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_test', models.IntegerField()),
                ('id_user', models.IntegerField()),
                ('involved', models.BooleanField()),
                ('rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Macroaree',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Macroaree_test',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_macroaree', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ay', models.IntegerField(verbose_name=4)),
                ('date', models.DateField()),
                ('online', models.BooleanField()),
            ],
        ),
    ]
