# Generated by Django 4.2.4 on 2023-08-05 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unitus_', '0003_availability_department_macroaree_macroaree_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='macroaree_test',
            name='id_test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='unitus_.test'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='id_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unitus_.test'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unitus_.user'),
        ),
        migrations.AlterField(
            model_name='macroaree_test',
            name='id_macroaree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unitus_.macroaree'),
        ),
    ]
